### ISSUE TITLE
Battery shows percentage with decimal.

### ISSUE THREAD

**Issue by Vinestou** [pilotak/homeassistant-attributes#1]
It works great but it show all my added batteries with a decimal.

```
  - platform: attributes
    friendly_name: 'Batteries'
    attribute: battery_level
    unit_of_measurement: '%'
    entities:
      - binary_sensor.xiaomi_door_sensor_1
      - binary_sensor.xiaomi_door_sensor_2
      - binary_sensor.xiaomi_motion_sensor_1
      - binary_sensor.xiaomi_motion_sensor_2
      - binary_sensor.xiaomi_motion_sensor_3
      - binary_sensor.xiaomi_motion_sensor_4
```
100.0 % should be 100 %

All the batteries that automatically get created in HA as sensors etc use without decimal.

**Comment by Vinestou** [comment]
Any update?

**Comment by aptonline** [comment]
I'm looking into this also , maybe there is a way to do it from a templating perspective.

**Comment by pilotak** [comment]
Sorry for the late answer i somehow turned off notifications on issues
similar to https://github.com/pilotak/homeassistant-attributes/issues/11 i will look into it

**Comment by pilotak** [comment]
@Vinestou , @aptonline   done, could you please test against the master branch, before releasing?

**Comment by aptonline** [comment]
@pilotak OK just tested and its still showing the decimal place. Is there any change in config needed?

**Comment by aptonline** [comment]
Ok still showing with the decimal point. Here is my config:

```
  - platform: attributes
    friendly_name: "Batteries"
    attribute: battery_level
    unit_of_measurement: "%"
    round_to: 0
    entities:
      - binary_sensor.attic_sensor_motion
      - binary_sensor.bedroom_sensor_motion
      - binary_sensor.kitchen_sensor_motion
```

**Comment by pilotak** [comment]
Hm, that's strange I have tested it. Could you please turn the debug on?
```yaml
logger:
 default: warning
 logs:
  custom_components.attributes: debug
```
