### ISSUE TITLE
Entity IDs that start with numbers fail to work

### ISSUE THREAD

**Issue by stratplayer** [pilotak/homeassistant-attributes#14]
When trying to extract attributes from the Entity ID named **binary_sensor.320i_windows** I receive the following error in the logs for HA

`Could not attribute sensor for binary_sensor.320i_windows: TemplateSyntaxError: expected token 'end of print statement', got 'i_windows'`

This is using this YAML to access

```yaml  
  - platform: attributes
    friendly_name: BMW Driver Windows
    attribute: windowDriverFront
    entities:
      - binary_sensor.320i_windows
```
When I renamed my Entity ID to **binary_sensor.bmw_windows** it works fine using this YAML. In the Discord channel Vasiley said using numbers could be the issue, he was right.

```yaml  
  - platform: attributes
    friendly_name: BMW Driver Windows
    attribute: windowDriverFront
    entities:
      - binary_sensor.bmw_windows
```
