### ISSUE TITLE
Sensor Wildcard

### ISSUE THREAD

**Issue by Tom-ahawk** [pilotak/homeassistant-attributes#2]
Nice integration!

It would make the integration more dynamic  if a sensor wildcard can be used, like how the Monster card uses wildcard (https://github.com/custom-cards/monster-card).

```
sensor:  
  - platform: attributes
    friendly_name: "Batteries"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
     - sensor.myslipo_1_0
     - sensor.*smoke*
     - sensor.*water*
     - sensor.*burglar*device*
```

Cheers.
