### ISSUE TITLE
How to use value_template?

### ISSUE THREAD

**Issue by bhessen** [pilotak/homeassistant-attributes#23]
Hi, I am trying to get sensors for all valve positions of my thermostats. Those are within the 'level' attribute as a number between 0 and 1. 

I would like to have those values between 0 and 100 %, but I am having troubles getting the syntax right. I tried some variations of this:
```
sensor:  
  - platform: attributes
    friendly_name: "Ventilposition"
    attribute: "level"
    unit_of_measurement: "%"
    value_template: "{{ (value*100) | float }}"  
    entities:
      - climate.heizkoerper_arbeitszimmer
      - climate.heizkoerper_bad
      - climate.heizkoerper_kueche
      - climate.heizkoerper_schlafzimmer
      - climate.heizkoerper_wohnzimmer
```

But this gives me 'unknown'. Could somebody give a hint where I am going wrong? I am still in the learning curve for the Jinja notation, so any help would be appreciated.

**Comment by pilotak** [comment]
Hi you need to adjust the template
```yaml
value_template: "* 100 | float"  
```

You could see the output template by turning on the debug
```yaml
logger:
 default: warning
 logs:
  custom_components.attributes: debug
```
