### ISSUE TITLE
Cannot get data from entity

### ISSUE THREAD

**Issue by domerich** [pilotak/homeassistant-attributes#35]
I was looking for this feature a long time but cannot get it to work.

So I have a tuya floor heating control unit.

Acorrding to the log it gives the following data:

```
"home_assistant": {
          "name": "Fu\u00dfbodenheizung ",
          "name_by_user": null,
          "disabled": false,
          "disabled_by": null,
          "entities": [
            {
              "disabled": false,
              "disabled_by": null,
              "entity_category": null,
              "device_class": null,
              "original_device_class": null,
              "icon": null,
              "original_icon": null,
              "unit_of_measurement": null,
              "state": {
                "entity_id": "climate.fussbodenheizung",
                "state": "heat",
                "attributes": {
                  "hvac_modes": [
                    "off",
                    "heat"
                  ],
                  "min_temp": 5.0,
                  "max_temp": 35.0,
                  "target_temp_step": 1.0,
                  "current_temperature": 22.0,
                  "temperature": 25.0,
                  "friendly_name": "Fu\u00dfbodenheizung ",
                  "supported_features": 1
                },
                "last_changed": "2023-02-15T13:48:03.755345+00:00",
                "last_updated": "2023-02-15T13:56:00.380026+00:00"
              }
            }
          ]
        }
```

so I want to read the to be created entity
`current_temperature`

which I created in the config

```
sensor:
  - platform: attributes
    friendly_name: "Fussbodenheizung_current_temperature"
    attribute: current_temperature
    device_class: temperature
    entities:
      - climate.fussbodenheizung
```

but after restart I get "unkown" so where did I go wrong?
