### ISSUE TITLE
"This entity is no longer being provided by the attributes integration"

### ISSUE THREAD

**Issue by witchdr** [pilotak/homeassistant-attributes#39]
I have recently had an issue validating my `configuration.yaml` file with an error regarding this integration. I resolved it by updating it to the latest version (v1.2.1) in HACS. But now I'm facing a new issue.

I am using the attributes platform to surface the outdoor temperature from the `weather.home` sensor. This has worked fine for a long time but is now reporting "This entity is no longer being provided by the attributes integration."

My `configuration.yaml` contains:

```
  - platform: attributes
    friendly_name: 'Outdoor Temperature'
    attribute: temperature
    unit_of_measurement: '°C'
    entities:
      - weather.home

```

The state of weather.home.temperature in my system right now is 16.3
