### ISSUE TITLE
extraction of value from attribute not working

### ISSUE THREAD

**Issue by Berni1983** [pilotak/homeassistant-attributes#42]
Dear all.

i use the following code in the config file, but the new created sensor shows no value.
what do i wrong. Thanks for your help.

sensor:
- platform: attributes
    friendly_name: "el.cost.allin.12-13"
    attribute: Hour 12-13
    unit_of_measurement: "ct/kWh"
    entities:
      - sensor.epex_spot_price_allin

![image](https://github.com/pilotak/homeassistant-attributes/assets/106546877/bee51ce3-633a-41c6-8811-9f429cf17ea8)

**Comment by pilotak** [comment]
your indetion is wrong, and try to wrap the `attribute` as string because it includes space

```yaml
- platform: attributes
  friendly_name: "el.cost.allin.12-13"
  attribute: "Hour 12-13"
  unit_of_measurement: "ct/kWh"
  entities:
    - sensor.epex_spot_price_allin
```
