### ISSUE TITLE
Support state_class so it can be used with Long-term Statistics

### ISSUE THREAD

**Issue by danielskowronski** [pilotak/homeassistant-attributes#44]
As per https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics the `state_class` seems to be a requirement for exposed attributes to be covered by long-term statistics. This allows them to be rendered in [Statistics graph card](https://www.home-assistant.io/dashboards/statistics-graph/) so it looks like Grafana without Grafana.

It should be fairly easy to pass this additional field to newly created entities.

**Comment by pilotak** [comment]
Happy to accept PR

**Comment by hmakmur** [comment]
Until there is a code change, you can easily fix this by adding entry in your customize.yaml. This is how i fixed all those other sensors that lack certain attributes I need. 
Example:
```
sensor.freezer_downstairs:
  state_class: measurement
sensor.pingdrivewaycam_round_trip_time_avg:
  state_class: measurement
sensor.motion_battery:
  state_class: measurement

```
