### ISSUE TITLE
Error with zigate entities

### ISSUE THREAD

**Issue by arkpoah** [pilotak/homeassistant-attributes#6]
Hello,

I'm trying to get sensors for battery_level of my zigate entities, I did that : 
```yaml
 - platform: attributes
   friendly_name: "Batteries"
   attribute: battery_level
   unit_of_measurement: "%"
   entities:
     - zigate.00158d000214f0ad
     - zigate.00158d00025d8c7b
     - zigate.00158d00025d8c8c
     - zigate.00158d00025d8cdd
```
battery_level sensors are well created but state stays on 'unknown'
I have errors like that when it tries to update it : 
> ERROR (MainThread) [custom_components.attributes.sensor] Could not attribute sensor for zigate.00158d00025d8c8c: TemplateSyntaxError: expected token 'end of print statement', got 'd00025d8c8c'
> ERROR (MainThread) [custom_components.attributes.sensor] Could not render icon template Chambre Clément: TemplateSyntaxError: expected token 'end of statement block', got 'd00025d8c8c'

Thanks
