### ISSUE TITLE
Issue - cant get this working at all ?

### ISSUE THREAD

**Issue by JamieP83** [pilotak/homeassistant-attributes#7]
Hey,
i cant seem to get this to work at all?

HassOS 3.5
--

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/London
version | 0.101.3
virtualenv | false

```
  - platform: attributes
    friendly_name: "TP_Link - Current Power Watts"
    attribute: current_power_w
    #unit_of_measurement: "w"
    entities:
      - switch.gaming_desk

  - platform: attributes
    friendly_name: "BatteriesAttributes"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - sensor.bar_sensor_temperature
      - sensor.front_porch_indoor_sensor_light_level
      - sensor.front_porch_indoor_sensor_temperature
```
